# See https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html

namespace: fluidware
name: cloudnative
version: 0.1.0
readme: README.md
authors:
  - Michele Azzolari (github.com/macno)
description: Collection for automate Cloud Native tools management
license_file: LICENSE
tags:
  - cloudnative
  - cri
  - cni
  - kubernetes
repository: https://github.com/fluidware-team/ansible-collection-cloudnative
homepage: https://github.com/fluidware-team/ansible-collection-cloudnative
issues: https://github.com/fluidware-team/ansible-collection-cloudnative/issues
build_ignore:
# https://docs.ansible.com/ansible/devel/dev_guide/developing_collections.html#ignoring-files-and-folders
  - .gitignore
  - changelogs/.plugin-cache.yaml
