---
- name: Ensure .kube directory exists.
  ansible.builtin.file:
    path: ~/.kube
    state: directory
    mode: 0700

- name: join other control planes to Kubernetes master
  ansible.builtin.shell:
    test -e /etc/kubernetes/admin.conf || {{ k8s_join_command }} --control-plane --certificate-key {{ k8s_certificate_key }}
  register: join_controlplane_result
  changed_when: "'' !=  join_controlplane_result.stdout"

- name: Symlink the kubectl admin.conf to ~/.kube/conf.
  ansible.builtin.file:
    src: /etc/kubernetes/admin.conf
    dest: ~/.kube/config
    state: link
    mode: 0600
