---
- name: ensure grub cmdline is configured
  ansible.builtin.lineinfile:
    state: present
    dest: /etc/default/grub
    backrefs: yes
    regexp: "^GRUB_CMDLINE_LINUX="
    line: 'GRUB_CMDLINE_LINUX="systemd.unified_cgroup_hierarchy=1 cgroup_enable=cpuset cgroup_enable=memory swapaccount=1"'
  register: grub_cmdline_stat

- name: update grub if needed
  block:
    - name: update grub
      ansible.builtin.command: >
        update-grub
    - name: reboot
      ansible.builtin.reboot:
        reboot_timeout: 60
        boot_time_command: who -b
  when: grub_cmdline_stat is changed
