---
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Make sure crio unit is running
  ansible.builtin.systemd:
    state: started
    name: crio
    enabled: yes
